{% set name = "bat-extras" %}
{% set version = "2024.08.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eth-p/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2ff1b9104134f10721ef36580150365e94546e5b41b9a2a6eaa4851c5959b487
  patches: 0001-lib-opts.sh-fix-prefixes-with-embedded.patch

build:
  noarch: generic
  number: 0
  script:
    - bash build.sh --no-verify --install --prefix "$PREFIX"

requirements:
  host:
    - bash
    - go-shfmt
    - gzip
  run:
    - bash
    - bat
    - fzf
    - ripgrep
    - __unix

test:
  commands:
    - bat-modules --help
    - test -f "$PREFIX/bin/batdiff"
    - batgrep --help
    - test -f "$PREFIX/bin/batman"
    - test -f "$PREFIX/bin/batpipe"
    - batwatch --help
    - prettybat --help

about:
  home: https://github.com/eth-p/bat-extras
  summary: Bash scripts that integrate bat with various command line tools
  license: MIT
  license_family: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - blmaier
